238 Open API: Document an endpoint to return a single capital project
NYCPlanning/ae-zoning-api pull request #282
Opened 2024-05-20 19:29 UTC by dhochbaum-dcp

Fixed the issue in the CapitalProjectBudgeted schema, and added the `/capital-projects/{managingCode}/{capitalProjectid}` endpoint.

Completes #238

2024-05-20 21:18 UTC, TangoYankee approved these changes

2024-05-30 14:17 UTC, TangoYankee requested changes
FYSA: Rebasing to main will delete the `openapi/index.html` and then ignore any regeneration of it. This will prevent future conflicts from that file. This should make life a little easier. Conflicts will still happen with the yaml file- so it goes.

2024-05-30 14:17 UTC, TangoYankee commented on openapi/openapi.yaml
> +      summary: Find details about a specific capital project
```suggestion
      summary: 🚧 Find details about a specific capital project
```

2024-05-30 15:15 UTC, TangoYankee requested changes
resolve conflicts & consolidate to one commit and I'll approve

2024-05-30 19:20 UTC, dhochbaum-dcp commented
> resolve conflicts & consolidate to one commit and I'll approve

Resolved conflicts, will squash when merging.

2024-06-04 13:57 UTC, TangoYankee commented
> > resolve conflicts & consolidate to one commit and I'll approve
> 
> Resolved conflicts, will squash when merging.

Squashing is disabled

2024-06-04 14:25 UTC, dhochbaum-dcp commented
> > > resolve conflicts & consolidate to one commit and I'll approve
> > 
> > 
> > Resolved conflicts, will squash when merging.
> 
> Squashing is disabled. Only rebasing is enabled

I'm encountering issues attempting to squash locally.  Do you have a good set of instructions?

2024-06-04 15:24 UTC, TangoYankee commented on openapi/openapi.yaml
> +  /capital-projects/{managingCode}/{capitalProjectid}:
I missed this before but Id should be capitalized

```suggestion
  /capital-projects/{managingCode}/{capitalProjectid}:
```

2024-06-04 15:25 UTC, TangoYankee commented
> > > > resolve conflicts & consolidate to one commit and I'll approve
> > > 
> > > 
> > > Resolved conflicts, will squash when merging.
> > 
> > 
> > Squashing is disabled. Only rebasing is enabled
> 
> I'm encountering issues attempting to squash locally. Do you have a good set of instructions?

Standby

2024-06-04 16:01 UTC, TangoYankee commented
> > > > > resolve conflicts & consolidate to one commit and I'll approve
> > > > 
> > > > 
> > > > Resolved conflicts, will squash when merging.
> > > 
> > > 
> > > Squashing is disabled. Only rebasing is enabled
> > 
> > 
> > I'm encountering issues attempting to squash locally. Do you have a good set of instructions?
> 
> Standby

The heart of what we're doing is rewriting the history of the feature branch to make it more succinct. That way, when we place it in the shared history of main (which we never rewrite), we have an easy to read log of changes. [A better overview for squash v rebase than I could give](https://stackoverflow.com/questions/2427238/what-is-the-difference-between-merge-squash-and-rebase)

With that in mind, the first thing we'll do is a soft reset back to the last commit that came from main:
```
git reset  d6d9acc5ec5c110a72903c4a52a61894f023cdcb --soft
```

This gives us all of the relevant code changes while removing the commits from the history.

While we're here, I noticed that `Id` should be capitalized. So let's make that change in the source code before we commit.

```
/capital-projects/{managingCode}/{capitalProjectId}:
```

It also seems the non-200 endpoints seem to have gone missing from the `/boroughs/{boroughId}/community-districts/{communityDistrictId}/capital-projects:` just above the capital project endpoint. (I think git saw the duplicate code and calculated that they were literally the same lines, rather than the same code repeated in different places.) Anyway, Let's copy those back in:

```
  /boroughs/{boroughId}/community-districts/{communityDistrictId}/capital-projects:
    get:
      summary: 🚧 Find paginated capital projects within a specified community district
      operationId: findCapitalProjectsByBoroughIdCommunityDistrictId
      tags:
      - Capital Projects
      parameters:
        - $ref: "#/components/parameters/boroughIdParam"
        - $ref: "#/components/parameters/communityDistrictIdParam"
      responses:
        '200':
          description: An object containing pagination metadata and an array of capital projects for the community district
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CapitalProjectPage"
        '400':
          $ref: "#/components/responses/BadRequest"
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/InternalServerError"
```

We'll stage these changes to the code
```
git add openapi/openapi.yaml
```

Then commit
```
git commit -m "your message here"
```

Then rebase onto main
```
git rebase --onto origin main
```

Finally, force push your feature branch
```
git push origin 238/Open-API-Document-an-endpoint-to-return-a-single-capital-project --force-with-lease
```

2024-06-04 17:01 UTC, dhochbaum-dcp commented
Thanks, @TangoYankee.

2024-06-12 20:32 UTC, pratishta approved these changes
🚀 🚀 🚀 🚀 🚀 🚀 🚀

2024-06-12 20:34 UTC, TangoYankee approved these changes

2024-06-12 20:34 UTC, merged