243 Document Endpoints to get MVTs for Capital Data
NYCPlanning/ae-zoning-api pull request #284
Opened 2024-05-21 21:03 UTC by horatiorosa

#### Description
Endpoints for mapbox tiles for capital data

#### Tickets
 - Closes #243

2024-05-24 14:20 UTC, TangoYankee reviewed
The code changes meet spec. Waiting for its turn in the queue of endpoints (#278 ) before approval.

2024-05-30 14:14 UTC, TangoYankee requested changes

2024-05-30 14:14 UTC, TangoYankee commented on openapi/openapi.yaml
> +      summary: Mapbox Vector Tiles for capital projects
```suggestion
      summary: 🚧 Mapbox Vector Tiles for capital projects
```

2024-05-30 14:14 UTC, TangoYankee commented on openapi/openapi.yaml
> +      summary: Mapbox Vector Tiles for city council districts
```suggestion
      summary: 🚧 Mapbox Vector Tiles for city council districts
```

2024-05-30 14:14 UTC, TangoYankee commented on openapi/openapi.yaml
> +      summary: Mapbox Vector Tiles for community districts
```suggestion
      summary: 🚧 Mapbox Vector Tiles for community districts
```

2024-05-30 19:55 UTC, horatiorosa commented
@TangoYankee  check the alphabetization order. Let me know if that is OK.

2024-06-04 14:12 UTC, TangoYankee commented
> @TangoYankee check the alphabetization order. Let me know if that is OK.

Mmm, trying to alphabetize based on path parameters is weird. The way you have it seems fine.

2024-06-04 15:19 UTC, TangoYankee approved these changes

2024-06-04 15:21 UTC, merged